<?php
/**
 * ReferenciaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Smartlog
 *
 * API para cálculo de valor de frete,rastreamento de encomendas e CEP's atendidos na plataforma Smartlog
 *
 * OpenAPI spec version: 2.0.1
 * Contact: junior@sistemasmartlog.com.br
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReferenciaTest Class Doc Comment
 *
 * @category    Class
 * @description Referencia
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReferenciaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Referencia"
     */
    public function testReferencia()
    {
    }

    /**
     * Test attribute "numero_pedido"
     */
    public function testPropertyNumeroPedido()
    {
    }

    /**
     * Test attribute "pesototal"
     */
    public function testPropertyPesototal()
    {
    }

    /**
     * Test attribute "volumestotal"
     */
    public function testPropertyVolumestotal()
    {
    }

    /**
     * Test attribute "valortotal"
     */
    public function testPropertyValortotal()
    {
    }

    /**
     * Test attribute "notas_fiscais"
     */
    public function testPropertyNotasFiscais()
    {
    }

    /**
     * Test attribute "destinatario"
     */
    public function testPropertyDestinatario()
    {
    }
}
