<?php
/**
 * MdulosApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Smartlog
 *
 * API para cálculo de valor de frete,rastreamento de encomendas e CEP's atendidos na plataforma Smartlog
 *
 * OpenAPI spec version: 2.0.1
 * Contact: junior@sistemasmartlog.com.br
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MdulosApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MdulosApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cEPsAtendidosColetaPhpGet
     *
     * Consultar os CEP's onde a coleta está disponível.
     *
     */
    public function testCEPsAtendidosColetaPhpGet()
    {
    }

    /**
     * Test case for cEPsAtendidosEntregaPhpGet
     *
     * Consultar os CEP's onde a entrega está disponível.
     *
     */
    public function testCEPsAtendidosEntregaPhpGet()
    {
    }

    /**
     * Test case for cotacaoPhpPost
     *
     * Realizar cotação de valor de frete.
     *
     */
    public function testCotacaoPhpPost()
    {
    }

    /**
     * Test case for rastreamentoPhpGet
     *
     * Consultar o status da encomenda.
     *
     */
    public function testRastreamentoPhpGet()
    {
    }
}
